### ISSUE TITLE
Equivalent to #Assign?

### ISSUE THREAD

**Issue by cristoslc** [dansmith65/FileMaker-JSON-Functions#31]
It would be useful if there were an equivalent function to `#Assign()` from the FMP Standards #Parameters module. I realize that it's possible to do something equivalent with a loop at the start of each script, but that seems like a lot of boilerplate steps.

Is this something you're considering? Or are you avoiding it in this module because dynamic variable naming requires using `Evaluate()` and `Quote()`?

**Comment by jbante** [comment]
One argument against this to consider is that the practice of letting the logic of whatever created a parameter decide what variables to set instead of the logic of a script receiving it is questionable at best. We tolerate it with the #Assign function because the parsing/evaluation of a whole Let notation parameter all at once is just so darn efficient. I follow certain practices in my scripting to minimize unintended consequences, but I can't control for everything, and we're usually better off having less to think about rather than more — or having the more that we have to think about be in the form of large, easy-to-discover-and-interpret blocks of code rather than non-obvious side effects of more concise constructions. I'm not deeply familiar with how the JSON functions work, but my suspicion is that a JSON #Assign function would not have the same linear vs. quadratic performance advantage of the Let Notation version over repeated #Get calls.

**Comment by dansmith65** [comment]
I can see how an `#Assign()` function would be useful for someone transitioning to these functions from the Let Notation based functions. Although; I doubt I will work on this unless either I need it for my own use or someone sponsors it.

> One argument against this to consider is that the practice of letting the logic of whatever created a parameter decide what variables to set instead of the logic of a script receiving it is questionable at best.

I agree with this argument and it's the reason that I probably won't decide to write this type of function for my own use.

> I'm not deeply familiar with how the JSON functions work, but my suspicion is that a JSON #Assign function would not have the same linear vs. quadratic performance advantage of the Let Notation version over repeated #Get calls.

I think you're right. Currently, I'm using a caching system to speed up reading each value from the json sequentially. This system does introduce some overhead, though, so a `jsonAssign()` type function could potentially bypass the caching system. So, it may be slightly quicker, but I don't think speed would be the deciding factor for using this function.

**Comment by cristoslc** [comment]
It's more of a convenience than a necessity for me. I can appreciate the arguments against it, and labeling the underlying concept as an antipattern.

I can certainly write a custom function for use in my own solutions, so will close this Issue as resolved.
