### ISSUE TITLE
Unicode Line Separator (U+2028) not valid

### ISSUE THREAD

**Issue by naioboot** [dansmith65/FileMaker-JSON-Functions#37]
My JSON includes a U+2028 character that doesn't pass jsonValidate function, I get the following error message:

> Error: control character 0xd

The hex character sequence is: `e280a8`

Is this correct?

Thanks for your contribution

**Comment by naioboot** [comment]
Sorry, my mistake

**Comment by dansmith65** [comment]
I'm not sure where you're at with this, but I'm assuming you realized the function you mentioned is actually in this repository: https://github.com/geistinteractive/JSONCustomFunctions.

Non-ASCII characters don't *have* to be converted to hex based on json.org's documentation, but I think some parser's require some characters to be escaped (like control characters). Since the jsonValidate function uses BaseElement's plugin, it's up to whatever json library that plugin uses to determine what is valid json.

The easiest fix would be to substitute known-to-fail characters with their escaped hex equivalent, like I've done here: https://github.com/dansmith65/FileMaker-JSON-Functions/blob/d25297ed403fcd9fd264d0982cae192c4a0c95ef/Functions/z_jsonEncodeSupport.fmfn#L113.

**Comment by naioboot** [comment]
Thanks for your help Dan, I've just done what you suggested
